kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ default "zookeeper" .Values.pod.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "zookeeper.commonLabels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
