kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:{{ default "zookeeper" .Values.pod.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "zookeeper.commonLabels" . | indent 4 }}
rules:
- apiGroups:
  - zookeeper.pravega.io
  resources:
  - "*"
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
