language: go
go:
- '1.13.8'
sudo: required
env:
    global:
      - KUBERNETES_VERSION=v1.15.0
      - OPERATOR_SDK_VERSION=v0.17.0
      - KUBERNETES_CONFIG_FILE=$HOME/.kube/config
      - CHANGE_MINIKUBE_NONE_USER=true
      - MINIKUBE_VERSION=v1.11.0
    secure: dIXvb2BS2AwvQf+McXNClqoV4AjobYyc0/2b+zn4yMQ2v8gAW5V0w8Y3af6EnwOLe9Szke0RRHj/5ktxyrnQtBLsQhZd13GUItLuvIyD1fZZx9/djA7aII71fqKBVLVg2OR9VFltfPDB1B9NSPD3w4NJhyWdAzUORnqiNkQmOc+WGdCVYJ6olXZoq1rCVD+ysxssuWaHVD4ujbdLmwToFhQiGGbpdInZjdLUZ8FWLEJHl5uHkntrHESDBBjZ+ZHeF5jZYEUKjoV0xvapiI+lqp6mcWzaVkop78SbjlHnbQNjqH3mW6i0lI7dRyMPPURUBPNKvhvDlAbRjd7CU70ASJmI2rCgKQru5tfASaegeCzdGCp1fOn4bdvDgL+9NtxsojL6J4j5H9MPmSE6zZVLLQN/wA4IM7vB12o+O7pEM40WiZ7qtCsolIFWE53zx9Beuf7FQFv8Zz/pCfUctvZdyE53T41uuzZVQC+w+w5sj/1rrLgBCjPD1ghNZdN+y3GD7Sgaic03a+FiCTKnOOab9Dk6Pil0m4qbYLJdkKKLt/PvAw7nb9GEX36VPLWrG9xCXsJvzbiG+JQBYEpSQrzJYj9vuNScoWZuvu1I+cRIZsj26dPt9XXn2I/8uQSKBQlNzPAIOD1NCTLtRglVkgPf+BxNppTLV2BmBRQ4V9ZtpJQ=
services:
- docker
install:
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$KUBERNETES_VERSION/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBE_VERSION/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
  - curl -Lo operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/$OPERATOR_SDK_VERSION/operator-sdk-$OPERATOR_SDK_VERSION-x86_64-linux-gnu && chmod +x operator-sdk && sudo mv operator-sdk /usr/local/bin/
before_script:
  - sudo mount --make-rshared /
  - sudo minikube start --cpus=8 --memory=50000mb --disk-size=50000mb --vm-driver=none --bootstrapper=kubeadm --kubernetes-version=$KUBERNETES_VERSION
  - minikube update-context
  - JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
  # Show cluster information
  - kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
  - kubectl cluster-info
  - kubectl -n kube-system get pod -o wide
script:
- make check
- make test
- make test-e2e
- make clean
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    skip_cleanup: true
    script: make push
    on:
      branch: master
      tags: true
