replicas: 3

image:
  repository: pravega/zookeeper
  tag: 0.2.7
  pullPolicy: IfNotPresent

domainName:
labels: {}
ports: []

pod: {}
  # labels: {}
  # nodeSelector: {}
  # affinity: {}
  # resources: {}
  # tolerations: []
  # env: []
  # annotations: {}
  # securityContext:
  # terminationGracePeriodSeconds: 180

config: {}
  # initLimit: 10
  # tickTime: 2000
  # syncLimit: 2
  # quorumListenOnAllIPs: false

persistence: 
    enabled: true
    storageClassName: standard
    # specifying reclaim policy for PersistentVolumes
    # accepted values - Delete / Retain
    reclaimPolicy: Delete
    volumeSize: 20Gi

ephemeral: 
    enabled: false
    #emptydirvolumesource: {}
    #medium: ""/Memory
    #sizeLimit: 15Gi

hooks:
  image:
    repository: lachlanevenson/k8s-kubectl
    tag: v1.16.10
